# Generated by Django 4.2.22 on 2025-07-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(max_length=30)),
                ('investor_Identification_Number', models.IntegerField()),
                ('investor_phone_number', models.IntegerField()),
                ('investor_location', models.CharField(max_length=40)),
                ('investor_email', models.EmailField(max_length=254)),
                ('investor_total_shares', models.IntegerField()),
                ('investor_share_value', models.IntegerField()),
            ],
        ),
    ]
