# Generated by Django 5.2.4 on 2025-07-11 18:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestorDetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorsprofile',
            name='investor_share_value',
        ),
        migrations.RemoveField(
            model_name='investorsprofile',
            name='investor_total_shares',
        ),
        migrations.AddField(
            model_name='investorsprofile',
            name='investor_date_of_birth',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 18, 37, 7, 560050, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
